### PR TITLE
Ahamada mbaraka patch 1

### PR DESCRIPTION
**Pull request by AhamadaMBARAKA**
Update API documentation to reflect final implementation

### CODE REVIEW

**Comment by GlennCavarle** [comment]
I'm not sure that we should present the actual data in the documentation.
It would be better to use sample data that are not related to customer.

**Comment by GlennCavarle** [comment]
This seems to be ok for me.
Just on detail : the json is malformed in events.rst at line 374 (a quote " is missing).
I will close (squash and merge) the pr monday morning.

**Comment by AhamadaMBARAKA** [comment]
ok , thanks Gleen

**Comment by AhamadaMBARAKA** [comment]
Ok, thanks Glenn .

**Pull request merged**
