### PR TITLE
(tck) - Changed the way selling options are handled - refs #2561

### PR DESCRIPTION
**Pull request by Fabrice-li**
It is now using the option table to work with domains.
The command './symfony doctrine:build-model' is required to create internal files.

### CODE REVIEW

**Comment by betaglop** [comment]
Why didn't you just overload the action::getForm() method instead of overloading action::executeIndex() ?

**Comment by Fabrice-li** [comment]
I am not sure to understand the question. getForm was used to create the widgets. Since I created a new module, it is no longer useful. Maybe I did not need to overload executeIndex though. I am still learning Symfony. ;)

**Comment by betaglop** [comment]
```php
     public function executeIndex(sfWebRequest $request)
     {
-      $this->form = $this->getForm();
+      $this->form = new OptionTckForm();
     }
```
```php
-    public function executeChange(sfWebRequest $request)
+    public function executeUpdate(sfWebRequest $request)
     {
-      $this->form = $this->getForm();      
-      $params = $request->getParameter('Options');
-      
+      $this->getContext()->getConfiguration()->loadHelpers('I18N');
+      $this->form = new OptionTckForm();     
+      $params = $request->getPostParameters();
+
```

IMO you should rather overload the ```action::getForm()``` than call directly a specific ```Form::__construct()``` twice:

```php
     public function executeIndex(sfWebRequest $request)
     {
-      $this->form = $this->getForm();
+      $this->form = $this->getForm();
     }
```
```php
-    public function executeChange(sfWebRequest $request)
+    public function executeUpdate(sfWebRequest $request)
     {
-      $this->form = $this->getForm();      
-      $params = $request->getParameter('Options');
-      
+      $this->getContext()->getConfiguration()->loadHelpers('I18N');
+      $this->form = $this->getForm();
+      $params = $request->getPostParameters();
+
```
```php
  protected function getForm()
  {
    return new OptionTckForm;
  }
```

Doing it this way, if you want one day to change the target form, you will only have to change it in one place and everything should be consistent.

**Comment by Fabrice-li** [comment]
Yes of course ! That's basic programming. I missed that. :o

**Comment by betaglop** [comment]
Ok, I'll change it in the master branch.

**Pull request merged**
