### PR TITLE
(pub) - Standardize color between the selling screen and the …

### PR DESCRIPTION
**Pull request by Fabrice-li**
…simplified version - refs #2295

### CODE REVIEW

**Comment by betaglop** [comment]
Is this really necessary ?
'Cause in the simplified GUI the goal was not to distinguish printed tickets and integrated one... knowing that their color are different in the complete GUI (gray and salmon), what is the basis for the simplified GUI ? First we chose the integrated one, gray.

First let's answer this question before merging the branches...

**Comment by betaglop** [comment]
Hey Fabrice,

What's up about my question here?

Thx,

**Comment by Fabrice-li** [comment]
Still pending. 
I did not know the color meanings. What you say makes sense.

**Comment by betaglop** [comment]
Ok, after a private discussion with the project team, we'll stay on the gray color.

**Pull request closed without merging**
