### PR TITLE
 (tck) - Activated the search input on contact field in the order page - refs #3024

### PR DESCRIPTION
**Pull request by Fabrice-li**

### CODE REVIEW

**Comment by betaglop** [comment]
are you sure about the "orWhere" of your request ? I don't remember how it has been done before, and it seems redundant with the Contact_Index search doesn't it ?

**Comment by Fabrice-li** [comment]
Without that condition, there is no filter but I might miss something. What is the Contact_Index search ?

**Comment by betaglop** [comment]
```
+  actAs:
+    Searchable:
```

This is useless until you add searchable fields.
Thus you might remove your actual search query from the Order entities and play with the Contact_Index table (```Doctrine::getTable('Contact')->search($search.'*')```) to get back contact ids, then do a kind of:
```sql
SELECT * FROM order_table o LEFT JOIN o.Transaction t WHERE t.contact_id IN ([IDS]);
```

Even if this can be optimized, this is only an idea...

**Comment by Fabrice-li** [comment]
I close this and submit another request.

**Pull request closed without merging**
